apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-spring-observability
  name: demo-spring-observability
spec:
  selector:
    matchLabels:
      app: demo-spring-observability
  template:
    metadata:
      labels:
        app: demo-spring-observability
    spec:
#      securityContext:
#        fsGroup: 472
#        supplementalGroups:
#          - 0
      containers:
        - name: demo-spring-observability
          image: demo-spring-observability:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-dso
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-spring-observability-service
spec:
  ports:
    - port: 3080
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo-spring-observability
  sessionAffinity: None
  type: LoadBalancer
