spring:
  application:
    name: train-webapp-metrics
  threads:
    virtual:
      enabled: true

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    health:
      probes:
        enabled: true
